name: build

# Controls when the action will run. Triggers the workflow on push or
# pull request events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          pacboy: >-
            autoconf
            autoconf-archive
            automake
            gettext:p

      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./bootstrap
          ./configure
